# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e34fcf1a43690af70a5bf860cdf146b6a5b03f5a9ad45ba0b5c81d21967a5ad3e78fde1c8139b19fe006484fe89d09c43990866ebbfe8ec6496b3d9419cc2c48

test:
  secret_key_base: 7d13a9efa96461fab760db5ddbc303b42743b06bc3b3b660f5bae03f2828abcda5b25bded20a9979880b327f81cd13567c1dc260e4f1fcbdcba5268b25c53c9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
